// This file is a designated placeholder for game content generated by AI tools.
// For example, new materials or blueprints created with the Dev Tool can be
// saved here and then imported into the main game data files.

// To make this file a module and prevent errors, we add a placeholder export.
export const placeholder = true;
